GET http://localhost:3001/api/patients/ HTTP/1.1

#####
POST http://localhost:3001/api/patients/ HTTP/1.1
Content-Type: application/json

{
  "name": "John Galt",
  "dateOfBirth": "1970-04-25",
  "ssn": "250470-555L",
  "gender": "male",
  "occupation": "Engineer"
}
